---
ConnectionStrings:
  Elasticsearch.off: server=http://localhost:9200
  Cache.off: provider=redis;server="localhost,abortConnect=false"
  MessageBus.off: provider=redis;server="localhost,abortConnect=false"
  Metrics.off: provider=statsd;server=10.0.0.5;
  Queue.off: provider=redis;server="localhost,abortConnect=false"
  Storage.off: ''
  Email.off: 'smtps://user:password@domain.com:587'
  LDAP.off: ''
  OAuth: FacebookId=395178683904310;GitHubId=7ef1dd5bfbc4ccf7f5ef;GoogleId=809763155066-enkkdmt4ierc33q9cft9nf5d5c02h30q.apps.googleusercontent.com;MicrosoftId=000000004C137E8B;SlackId=34500115540.177239122322;

  # Base url for the ui used to build links in emails and other places.
BaseURL: https://be.exceptionless.io

# Controls whether users can signup.
EnableAccountCreation: true

# Email
# SmtpFrom:Exceptionless <noreply@exceptionless.io>

# Exceptionless Client Settings
ExceptionlessServerUrl: https://collector.exceptionless.io
InternalProjectId: 50ca6b2423d6c8493020b823
StripePublishableApiKey: pk_live_QTiVo5Fqv7uNScqIpd1Ns9gX