version: 4.0.{build}
os: Visual Studio 2017
configuration: Release
clone_depth: 2

pull_requests:
  do_not_increment_build_number: true

environment:
  JAVA_HOME: C:\Progra~1\Java\jdk1.8.0
  API_URL: https://#{api.hostheader}
  BUILD_REPO_URL:
    secure: vuYBT6D5arel88+Py/H3nnMPd4hInIXvr2cwhJaZSSSvJnmg+9sX1P5+bTWaJskYpGztHVMg0Iq7hgUCMKjh23w8WBrutLiUsixRE0LBjroIVJaRsYG1okSko0fNKVOCUMQAue0lh2sYqQ/TQlDbwg==
  BUILD_APP_REPO_URL:
     secure: vuYBT6D5arel88+Py/H3nnMPd4hInIXvr2cwhJaZSSSvJnmg+9sX1P5+bTWaJskYpGztHVMg0Iq7hgUCMKjh23w8WBrutLiUsixRE0LBjroIVJaRsYG1okSko0fNKVOCyOLKGt19Qrk45/TrTFlGMQ==

init:
  - git config --global core.autocrlf true
  - git config --global user.email "builds@exceptionless.io"
  - git config --global user.name "AppVeyor CI"
  - ps: $env:GIT_HASH = $env:APPVEYOR_REPO_COMMIT.Substring(0, 10)

assembly_info:
  patch: true
  file: src\GlobalAssemblyInfo.cs
  assembly_version: "{version}.0"
  assembly_file_version: "{version}.0"
  assembly_informational_version: "{version} $(GIT_HASH)"

before_build:
  - nuget restore -verbosity quiet
  - ps: .\build\Start-ElasticSearch.ps1 -NodeCount 1 -StartKibana $false

build:
  parallel: true
  verbosity: quiet

before_test:
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

test:
  assemblies:
    - '**\*.Tests.dll'

after_test:
  - ps: .\build\Push-Artifacts.ps1

artifacts:
  - path: release\*.zip
    name: ReleaseArtifacts

before_deploy:
  - ps: .\build\Create-Release.ps1

deploy:
  provider: GitHub
  auth_token:
    secure: 0s81q7bweVLTFSOKxnIhan7el6bIFiN8HJ1kYJzOkeFXX7wgGSq9bs/rV53X9qpf
  artifact: ReleaseArtifacts
  draft: true
  on:
    branch: master
    appveyor_repo_tag: true

notifications:
  - provider: Slack
    channel: '#notifications'
    auth_token:
      secure: GniMpFE62HprSyQNQoej/fBOAdbQe8EMWAMMNXX0s2JxeNePjemiO1bCf4eYweE4p70mm0sCwMjeEP/Ps9aTMA==
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: false