version: 3.2.{build}
os: Visual Studio 2015
configuration: Release
clone_depth: 2

environment:
  JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
  ES_VERSION: 1.7.3
  API_URL: https://#{api.hostheader}
  BUILD_REPO_URL:
    secure: vuYBT6D5arel88+Py/H3nnMPd4hInIXvr2cwhJaZSSSvJnmg+9sX1P5+bTWaJskYpGztHVMg0Iq7hgUCMKjh23w8WBrutLiUsixRE0LBjroIVJaRsYG1okSko0fNKVOCUMQAue0lh2sYqQ/TQlDbwg==
  BUILD_APP_REPO_URL:
     secure: vuYBT6D5arel88+Py/H3nnMPd4hInIXvr2cwhJaZSSSvJnmg+9sX1P5+bTWaJskYpGztHVMg0Iq7hgUCMKjh23w8WBrutLiUsixRE0LBjroIVJaRsYG1okSko0fNKVOCyOLKGt19Qrk45/TrTFlGMQ==

init:
  - git config --global core.autocrlf true
  - git config --global user.email "builds@exceptionless.io"
  - git config --global user.name "AppVeyor CI"

install:
  - ps: $env:GIT_HASH = $env:APPVEYOR_REPO_COMMIT.Substring(0, 10)

assembly_info:
  patch: true
  file: Source\GlobalAssemblyInfo.cs
  assembly_version: "{version}.0"
  assembly_file_version: "{version}.0"
  assembly_informational_version: "{version} $(GIT_HASH)"

before_build:
  - nuget restore -verbosity quiet

build:
  parallel: true
  verbosity: minimal

before_test:
  - ps: .\Libraries\Start-ElasticSearch.ps1
  #- ps: .\Libraries\Enable-Rdp.ps1

after_test:
  - ps: .\Libraries\Push-Artifacts.ps1

artifacts:
  - path: release\*.zip
    name: ReleaseArtifacts

before_deploy:
  - ps: .\Libraries\Create-Release.ps1

deploy:
  provider: GitHub
  auth_token:
    secure: 0s81q7bweVLTFSOKxnIhan7el6bIFiN8HJ1kYJzOkeFXX7wgGSq9bs/rV53X9qpf
  artifact: ReleaseArtifacts
  draft: true
  on:
    branch: master
    appveyor_repo_tag: true

notifications:
  - provider: Slack
    auth_token:
      secure: PigIGGo7UUDwdb0KGM/s7OfpAng/OMJx7q33jKfzudFBiXi1EBEd0DRmkbCc7CiX
    channel: notifications
