version: '3.4'

services:
  api:
    depends_on:
      - elasticsearch
    image: exceptionless/api-ci
    environment:
      AppMode: Development
      ConnectionStrings__Elasticsearch: http://elasticsearch:9200
      ConnectionStrings__Redis: redis,abortConnect=false
      RunJobsInProcess: 'false'
      StorageFolder: /app/storage
    ports:
      - 5000:80
    volumes:
      - appdata:/app/storage

  jobs:
    depends_on:
      - api
    image: exceptionless/job-ci
    command: run-all
    environment:
      AppMode: Development
      ConnectionStrings__Elasticsearch: http://elasticsearch:9200
      ConnectionStrings__Redis: redis,abortConnect=false
      StorageFolder: /app/storage
    volumes:
      - appdata:/app/storage

  ui:
    image: exceptionless/ui-ci
    environment:
      AppMode: Development
      BaseUrl: http://ex-api.localtest.me:5000
    ports:
      - 5100:80

  elasticsearch:
    image: slideroom/elasticsearch:98
    environment:
      bootstrap.memory_lock: 'true'
      discovery.type: single-node
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      xpack.security.enabled: 'false'
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1 
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    depends_on:
      - elasticsearch
    image: slideroom/kibana:116
    ports:
      - 5601:5601

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
 
volumes:
  esdata:
    driver: local
  appdata:
    driver: local
