version: '3.5'

# NOTE: This docker-compose file is for running services required to work on Exceptionless.
# For self-hosting, look here: https://github.com/exceptionless/Exceptionless/tree/master/samples

services:
  elasticsearch:
    image: exceptionless/elasticsearch:7.14.0
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'false'
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    ports:
      - 9200:9200

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:7.14.0
    ports:
      - 5601:5601

  apm:
    image: docker.elastic.co/apm/apm-server:7.14.0
    depends_on:
      - elasticsearch
    ports:
      - 8200:8200
    command: >
       apm-server -e
         -E apm-server.rum.enabled=true
         -E setup.kibana.host=kibana:5601
         -E setup.template.settings.index.number_of_replicas=0
         -E apm-server.kibana.enabled=true
         -E apm-server.kibana.host=kibana:5601
         -E output.elasticsearch.hosts=["elasticsearch:9200"]

  otel:
    image: otel/opentelemetry-collector:latest
    ports:
      - 4317:4317
    volumes:
      - ./otel-config.yml:/etc/otel-config.yaml:ro
    command: [ "--config=/etc/otel-config.yaml", "--log-level=DEBUG" ]

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  ui:
    image: exceptionless/ui:latest
    environment:
      AppMode: Development
      EX_ApiUrl: http://localhost:5000
      EX_Html5Mode: 'true'
    ports:
      - 5100:80

  ready:
    image: dadarek/wait-for-dependencies
    command: elasticsearch:9200
    depends_on:
      - elasticsearch

