appMode: Staging
appScope: dev
api:
  image:
    repository: exceptionless/api-ci
  defaultDomain: dev-api.exceptionless.io
  domains:
    - dev-api.exceptionless.io
app:
  image:
    tag: "2.9.2"
  defaultDomain: dev-app.exceptionless.io
  domains:
    - dev-app.exceptionless.io
collector:
  defaultDomain: dev-collector.exceptionless.io
  domains:
    - dev-collector.exceptionless.io
jobs:
  image:
    repository: exceptionless/job-ci

config:
  EX_EnableSnapshotJobs: "false"