apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: ex-prod
  namespace: ex-prod
spec:
  version: 7.5.2
  image: exceptionless/elasticsearch:7.5.2 # https://github.com/exceptionless/Exceptionless/tree/master/build/docker/elasticsearch
  secureSettings:
    - secretName: ex-prod-snapshots
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: main
    count: 3
    config:
      node.master: true
      node.data: true
      node.ingest: true
      action.destructive_requires_name: true
      # if not setting max_map_count in an init container, then use this setting
      #node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms9g -Xmx9g
          resources:
            requests:
              memory: 18Gi
              cpu: 4
            limits:
              memory: 18Gi
              cpu: 4
        # related to "node.store.allow_mmap: false" setting above
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 750Gi
        storageClassName: managed-premium

---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: ex-prod
  namespace: ex-prod
spec:
  version: 7.5.2
  count: 1
  elasticsearchRef:
    name: ex-prod
  config:
    xpack.monitoring.enabled: true
  http:
    tls:
      selfSignedCertificate:
        disabled: true

