version: latest

app:
  replicaCount: 1
  defaultDomain:
  domains: []
  image:
    repository: exceptionless/app
    pullPolicy: IfNotPresent

api:
  replicaCount: 1
  defaultDomain:
  domains: []
  image:
    repository: exceptionless/api
    pullPolicy: IfNotPresent

jobs:
  image:
    repository: exceptionless/job
    pullPolicy: IfNotPresent
  closeInactiveSessions:
    replicaCount: 1
  dailySummary:
    replicaCount: 1
  eventNotifications:
    replicaCount: 1
  eventPosts:
    replicaCount: 1
  eventUserDescriptions:
    replicaCount: 1
  mailMessage:
    replicaCount: 1
  stackEventCount:
    replicaCount: 1
  webhooks:
    replicaCount: 1
  workitem:
    replicaCount: 1
  eventUsage:
    replicaCount: 1

config: {}
#  key: value

service:
  type: ClusterIP

elasticsearch:
  connectionString:
  image:
    repository: exceptionless/elasticsearch
    tag: 8.11.0
    pullPolicy: IfNotPresent

redis:
  connectionString:
  image:
    repository: redis
    tag: latest
    pullPolicy: IfNotPresent

storage:
  connectionString:

cache:
  connectionString:

metrics:
  connectionString:

queue:
  connectionString:

email:
  connectionString:

messagebus:
  connectionString:
