version: "3.5"

services:
  exceptionless:
    image: exceptionless/exceptionless:latest
    ports:
      - 5200:8080
      - 9200:9200
    environment:
      EX_AppMode: Production
      #ASPNETCORE_URLS: http://+;https://+
      #ASPNETCORE_HTTPS_PORT: 5201
      #ASPNETCORE_Kestrel__Certificates__Default__Password: password
      #ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    volumes:
      - ex_ssldata:/https
      - ex_esdata:/usr/share/elasticsearch/data

  # Runs Kibana for working with Elasticsearch data directly. This is normally not needed and takes up resources when running.
  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:8.19.2
    ports:
      - 5601:5601

volumes:
  ex_esdata:
    driver: local
  ex_ssldata:
    driver: local
