name: Elasticsearch Docker Image CI

on:
  push:
    paths:
    - 'build/docker/elasticsearch/**'

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build custom Elasticsearch docker image
      working-directory: build/docker/elasticsearch
      run: |
        VERSION=$(sed -n 's/.*elasticsearch:\([^ ]*\).*/\1/p' Dockerfile)
        docker build . --tag exceptionless/elasticsearch:$VERSION
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push exceptionless/elasticsearch:$VERSION
        docker build . --tag docker.pkg.github.com/exceptionless/exceptionless/elasticsearch:$VERSION
        echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username ${{ github.actor }} --password-stdin
        docker push docker.pkg.github.com/exceptionless/exceptionless/elasticsearch:$VERSION
